### PR TITLE
CSS Variables + Better Web Component Styling

### PR DESCRIPTION
**Pull request by taybenlor**
This PR adds new CSS variables to the `runno-run` web component:

`--runno-editor-height`, `--runno-terminal-height`, `--runno-editor-max-height`, `--runno-terminal-min-height`.

The default look and layout behaviour of the web component has also been improved so that it works nicely without any styling.

### CODE REVIEW

**Comment by LukePrior** [comment]
I've had a chance to try this out but I've found that `--runno-editor-height` doesn't actually work unless `runno-editor` has `overflow:auto` set, I would suggest setting this on default but if that breaks iframe I would request that it is available to set as a CSS variable. Thanks

**Comment by taybenlor** [comment]
Did you try setting max height? `max-height` will effectively override `height`.

**Comment by LukePrior** [comment]
`max-height` doesn't seem to work:

image

**Comment by LukePrior** [comment]
I was also thinking that having a `max-height` option for the terminal in addition to a` min-height` could be useful.

**Comment by taybenlor** [comment]
Okay I'll keep fiddling with how these work. I was hoping the overflow behaviour would "just work" as a result of the flex rules I'd set.

I think for most people the best way to restrict the height of the editor will be to set a height on the `runno-run` element. For people (like you) who want more control over the individual pieces I think it would be better to have a way to compose together the editor, the terminal and the controls.

**Comment by LukePrior** [comment]
The problem is even with setting a height on the `runno-run` element I still encounter the overflow issue without using any of the CSS variables.

```
runno-run {
    max-height: 60vh;
}
```

image

The only way to get the element working for long code snippets is by setting the `--runno-editor-height` but that isn't ideal as I don't always want it at the maximum size.

**Comment by taybenlor** [comment]
Can you send me an example? I don't see that same behaviour.

Here I've edited a `runno-run` element on the Runno website to have a height of 400px and it comfortably scrolls:

Screen Shot 2022-04-07 at 11 05 11 pm

**Comment by taybenlor** [comment]
Yep I just had a play around and can replicate what you're describing. Looks like `overflow: auto` behaves nicely so I think that's a good default. PR would be great, thanks!

**Pull request merged**
